version: '2'

services:
    elk:
        build:
            context: elk-docker
            dockerfile: Dockerfile
        image: elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "5000:5000"

